apiVersion: mongodb.akleymk4.com/v1
kind: MongoDBCluster
metadata:
  labels:
    app.kubernetes.io/name: mongodb-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: mongodbcluster
spec:
  images:
    mongod: mongodb/mongodb-community-server:7.0.11-ubuntu2204
  imagePullPolicy: IfNotPresent
  resourceRequirements: {}
  shards:
    rs1: {}
  configServer:
    replicaSetId: "rs1"
    numReplicaSetNodes: 3
  routers:
    - configServerRSNames:
      - "rs1"
