apiVersion: mongodb.akleymk4.com/v1
kind: MongoDBCluster
metadata:
  labels:
    app.kubernetes.io/name: mongodb-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: mongodbcluster
spec:
  images:
    mongodb: mongodb/mongodb-community-server:7.0.11-ubuntu2204
  imagePullPolicy: IfNotPresent
  resourceRequirements:
    shard:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 2Gi
    configServer:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 512Mi
    router:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
  dbConnTimeout: 2000000000
  defaultRWConcern:
    defaultWriteConcern:
      w: majority
      wtimeout: 60000
    defaultReadConcern:
      level: "majority"
  shards:
    shrs1:
      numSecondaryNodes: 2
      numArbiterNodes: 0
  configServer:
    replicaSetId: "confrs1"
    numReplicas: 3
  routers:
    serviceType: "ClusterIP"
    numReplicas: 2
    servicePort: 27017
    port: 27017